package umg.proyectob;
import javax.swing.JOptionPane;


public class NuevoCupon extends javax.swing.JFrame {

    public NuevoCupon() {
        initComponents();
        ComboBoxPorcenoTotal.removeAllItems();
    ComboBoxPorcenoTotal.addItem("Porcentaje");
    ComboBoxPorcenoTotal.addItem("Monto fijo");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCode = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lblActive = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        ComboBoxPorcenoTotal = new javax.swing.JComboBox<>();
        ToggleOnOff = new javax.swing.JToggleButton();
        lblValue = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCode.setText("Codigo");

        lblDescription.setText("Descripcion");

        lblType.setText("Tipo");

        lblActive.setText("Activo");

        ComboBoxPorcenoTotal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ToggleOnOff.setText("On");

        lblValue.setText("Valor");

        btnClose.setText("Cerrar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnAdd.setText("Agregar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblCode)
                                .addGap(65, 65, 65))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblValue)
                                    .addComponent(lblDescription)
                                    .addComponent(lblActive)
                                    .addComponent(lblType))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescription)
                            .addComponent(txtCode)
                            .addComponent(txtValor)
                            .addComponent(ComboBoxPorcenoTotal, 0, 80, Short.MAX_VALUE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ToggleOnOff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(171, 171, 171))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClose)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCode)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValue)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescription)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxPorcenoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblType))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ToggleOnOff)
                    .addComponent(lblActive))
                .addGap(29, 29, 29)
                .addComponent(btnAdd)
                .addGap(15, 15, 15)
                .addComponent(btnClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
       // TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String codigo = txtCode.getText().trim();
        String descripcion = txtDescription.getText().trim();
        String tipoDescuento = (String) ComboBoxPorcenoTotal.getSelectedItem();

        if (codigo.isEmpty() || descripcion.isEmpty() || txtValor.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
            return;
        }

        double valor;

        try {
            valor = Double.parseDouble(txtValor.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El valor debe ser numérico.");
            return;
        }

        if (valor <= 0 || (tipoDescuento.equals("Porcentaje") && valor > 100)) {
            JOptionPane.showMessageDialog(this, "Ingrese un valor válido (entre 1 y 100 para porcentaje).");
            return;
        }

        for (Cupon c : Proyectob.cupones) {
            if (c.getCodigo().equalsIgnoreCase(codigo)) {
                JOptionPane.showMessageDialog(this, "El código ya está registrado.");
                return;
            }
        }

        boolean activo = ToggleOnOff.isSelected();

        Cupon cupon = new Cupon();
        cupon.setCodigo(codigo);
        cupon.setDescripcion(descripcion);
        cupon.setValor(valor);
        cupon.setEsPorcentaje(tipoDescuento.equals("Porcentaje"));
        cupon.setActivo(activo);

        Proyectob.cupones.add(cupon);

        JOptionPane.showMessageDialog(this, "Cupón '" + codigo + "' creado exitosamente.");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {
        String codigo = txtCode.getText().trim();
        String descripcion = txtDescription.getText().trim();
        String valorTexto = txtValor.getText().trim(); 
        boolean activo = ToggleOnOff.isSelected();
        String tipo = ComboBoxPorcenoTotal.getSelectedItem().toString();
        

        if (codigo.isEmpty() || descripcion.isEmpty() || txtValor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
            return;
        }

        double valor;
        try {
            valor = Double.parseDouble(txtValor.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El valor debe ser numérico.");
            return;
        }

        // Validación adicional
        if (valor <= 0) {
            JOptionPane.showMessageDialog(this, "El valor debe ser positivo.");
            return;
        }

        // Validar código único
        for (Cupon c : Proyectob.cupones) {
            if (c.getCodigo().equalsIgnoreCase(codigo)) {
                JOptionPane.showMessageDialog(this, "El código ya está registrado.");
                return;
            }
        }

        // Crear y guardar el cupón
        Cupon c = new Cupon();
        c.setCodigo(codigo);
        c.setDescripcion(descripcion);
        c.setValor(valor);
        c.setEsPorcentaje(tipo.equals("Porcentaje"));
        c.setActivo(activo);

        Proyectob.cupones.add(c);
        PuntosExtra.guardarTodo();
        JOptionPane.showMessageDialog(this, "Cupón '" + codigo + "' creado exitosamente.");
        this.dispose();
    
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxPorcenoTotal;
    private javax.swing.JToggleButton ToggleOnOff;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel lblActive;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblValue;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
